# List comprehension
# Examples from Whirlwind Guide to Python
# https://jakevdp.github.io/WhirlwindTourOfPython/11-list-comprehensions.html

# Basic list generation

# We can generate a list using a for loop
L = []
for n in range(12):
    L.append(n ** 2)
print(L)

# This is the same list generated by list comprehension
L = [n ** 2 for n in range(12)]
print(L)
# Translated: "construct a list consisting of the square of n for each n up to 11"

print("---")

# Multiple iteration

# Using loops
L = []
for i in range(2):
    for j in range(3):
        L.append((i, j))
print(L)

# And as list comprehension
L = [(i, j) for i in range(2) for j in range(3)]
print(L)

print("---")

# Conditional statements

# Using a for loop and an if statement
L = []
for val in range(20):
    if val % 3:
        L.append(val)
print(L)

# As list comprehension
L = [val for val in range(20) if val % 3 > 0]
print(L)

# Using a for loop and an if statement
L = []
for val in range(20):
    if val % 3:
        if val % 2:
            L.append(val)
        else:
            L.append(-val)
print(L)

# Using list comprehension
L = [val if val % 2 else -val for val in range(20) if val % 3]
print(L)
